##===- libepid/lib/libepid/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=epid

#
# Enable C++11
#
CPPFLAGS += -std=c++11

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
